version: "3.9"

services:
  pg:    
    image: postgres 
    restart: always    
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  

  nats:
    image: nats:2.9.6-alpine3.16
    ports:
      - "8222:8222"

      