version: "3.9"

services:
  pg:    
    image: postgres 
    restart: always    
    ports:
      - "5432:5432"
    environment:      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d/
    